export const countries = [
  "Abidjan, Ivory Coast",
  "Abu Dhabi, United Arab Emirates",
  "Accra, Ghana",
  "Adana, Turkey",
  "Addis Ababa, Ethiopia",
  "Ahmedabad, India",
  "Algiers, Algeria",
  "Almaty, Kazakhstan",
  "Amman, Jordan",
  "Amsterdam, Netherlands",
  "Ankara, Turkey",
  "Antananarivo, Madagascar",
  "Apia, Samoa",
  "Ashgabat, Turkmenistan",
  "Asmara, Eritrea",
  "Asuncion, Paraguay",
  "Athens, Greece",
  "Auckland, New Zealand",
  "Baghdad, Iraq",
  "Baku, Azerbaijan",
  "Bamako, Mali",
  "Bandar Seri Begawan, Brunei",
  "Bangkok, Thailand",
  "Bangui, Central African Republic",
  "Banjul, Gambia",
  "Barcelona, Spain",
  "Basseterre, Saint Kitts and Nevis",
  "Beijing, China",
  "Beirut, Lebanon",
  "Belgrade, Serbia",
  "Belmopan, Belize",
  "Berlin, Germany",
  "Bern, Switzerland",
  "Bishkek, Kyrgyzstan",
  "Bissau, Guinea-Bissau",
  "Bogota, Colombia",
  "Brasilia, Brazil",
  "Bratislava, Slovakia",
  "Brazzaville, Republic of the Congo",
  "Bridgetown, Barbados",
  "Brisbane, Australia",
  "Brussels, Belgium",
  "Bucharest, Romania",
  "Budapest, Hungary",
  "Buenos Aires, Argentina",
  "Cairo, Egypt",
  "Canberra, Australia",
  "Cape Town, South Africa",
  "Caracas, Venezuela",
  "Castries, Saint Lucia",
  "Chandigarh, India",
  "Chennai, India",
  "Chicago, United States",
  "Chisinau, Moldova",
  "Colombo, Sri Lanka",
  "Conakry, Guinea",
  "Copenhagen, Denmark",
  "Dakar, Senegal",
  "Damascus, Syria",
  "Dhaka, Bangladesh",
  "Dili, East Timor",
  "Djibouti, Djibouti",
  "Dodoma, Tanzania",
  "Doha, Qatar",
  "Douglas, Isle of Man",
  "Dubai, United Arab Emirates",
  "Dublin, Ireland",
  "Dushanbe, Tajikistan",
  "Edinburgh, United Kingdom",
  "Fort-de-France, Martinique",
  "Frankfurt, Germany",
  "Freetown, Sierra Leone",
  "Funafuti, Tuvalu",
  "Gaborone, Botswana",
  "Georgetown, Guyana",
  "Guatemala City, Guatemala",
  "Guayaquil, Ecuador",
  "Guwahati, India",
  "Hagatna, Guam",
  "Hamilton, Bermuda",
  "Hanoi, Vietnam",
  "Harare, Zimbabwe",
  "Havana, Cuba",
  "Helsinki, Finland",
  "Honiara, Solomon Islands",
  "Houston, United States",
  "Hyderabad, India",
  "Islamabad, Pakistan",
  "Istanbul, Turkey",
  "Jakarta, Indonesia",
  "Jerusalem, Israel",
  "Johor,Malaysia",
  "Johannesburg, South Africa",
  "Juba, South Sudan",
  "Kabul, Afghanistan",
  "Kampala, Uganda",
  "Kathmandu, Nepal",
  "Khartoum, Sudan",
  "Kigali, Rwanda",
  "Kingston, Jamaica",
  "Kingstown, Saint Vincent and the Grenadines",
  "Kinshasa, Democratic Republic of the Congo",
  "Kolkata, India",
  "Kuala Lumpur, Malaysia",
  "Kuwait City, Kuwait",
  "Kyiv, Ukraine",
  "La Paz, Bolivia",
  "Libreville, Gabon",
  "Lilongwe, Malawi",
  "Lima, Peru",
  "Lisbon, Portugal",
  "Ljubljana, Slovenia",
  "Lome, Togo",
  "London, United Kingdom",
  "Los Angeles, United States",
  "Luanda, Angola",
  "Lusaka, Zambia",
  "Luxembourg, Luxembourg",
  "Madrid, Spain",
  "Majuro, Marshall Islands",
  "Malabo, Equatorial Guinea",
  "Male, Maldives",
  "Managua, Nicaragua",
  "Manama, Bahrain",
  "Manila, Philippines",
  "Maputo, Mozambique",
  "Maracaibo, Venezuela",
  "Marigot, Saint Martin",
  "Maseru, Lesotho",
  "Minsk, Belarus",
  "Mogadishu, Somalia",
  "Monaco, Monaco",
  "Monrovia, Liberia",
  "Montevideo, Uruguay",
  "Moroni, Comoros",
  "Moscow, Russia",
  "Mumbai, India",
  "Muscat, Oman",
  "Nairobi, Kenya",
  "Nassau, Bahamas",
  "Naypyidaw, Myanmar",
  "N'Djamena, Chad",
  "New Delhi, India",
  "New York, United States",
  "Niamey, Niger",
  "Nicosia, Cyprus",
  "Nouakchott, Mauritania",
  "Nuku'alofa, Tonga",
  "Nur-Sultan, Kazakhstan",
  "Nuuk, Greenland",
  "Oranjestad, Aruba",
  "Osaka, Japan",
  "Oslo, Norway",
  "Ottawa, Canada",
  "Ouagadougou, Burkina Faso",
  "Pago Pago, American Samoa",
  "Palikir, Micronesia",
  "Panama City, Panama",
  "Paramaribo, Suriname",
  "Paris, France",
  "Patna, India",
  "Pekanbaru, Indonesia",
  "Peoria, United States",
  "Perth, Australia",
  "Phnom Penh, Cambodia",
  "Phoenix, United States",
  "Podgorica, Montenegro",
  "Port Louis, Mauritius",
  "Port Moresby, Papua New Guinea",
  "Port of Spain, Trinidad and Tobago",
  "Port-au-Prince, Haiti",
  "Porto Alegre, Brazil",
  "Porto-Novo, Benin",
  "Prague, Czech Republic",
  "Praia, Cape Verde",
  "Pretoria, South Africa",
  "Providence, United States",
  "Puebla, Mexico",
  "Pune, India",
  "Pyongyang, North Korea",
  "Quebec, Canada",
  "Quetzaltenango, Guatemala",
  "Quito, Ecuador",
  "Rabat, Morocco",
  "Rawalpindi, Pakistan",
  "Recife, Brazil",
  "Reykjavik, Iceland",
  "Riga, Latvia",
  "Riyadh, Saudi Arabia",
  "Road Town, British Virgin Islands",
  "Rome, Italy",
  "Rosario, Argentina",
  "Saint-Denis, Reunion",
  "Saint George's, Grenada",
  "Saint Helier, Jersey",
  "Saint John's, Antigua and Barbuda",
  "Saint Peter Port, Guernsey",
  "Saint Petersburg, Russia",
  "Saipan, Northern Mariana Islands",
  "Sale, Morocco",
  "Salem, United States",
  "Salt Lake City, United States",
  "Salvador, Brazil",
  "San Antonio, United States",
  "San Diego, United States",
  "San Francisco, United States",
  "San Jose, Costa Rica",
  "San Juan, Puerto Rico",
  "San Marino, San Marino",
  "San Salvador, El Salvador",
  "Sanaa, Yemen",
  "Santiago, Chile",
  "Santo Domingo, Dominican Republic",
  "Sao Paulo, Brazil",
  "Sapporo, Japan",
  "Sarajevo, Bosnia and Herzegovina",
  "Seattle, United States",
  "Semarang, Indonesia",
  "Seoul, South Korea",
  "Shanghai, China",
  "Sharjah, United Arab Emirates",
  "Shenyang, China",
  "Shenzhen, China",
  "Singapore, Singapore",
  "Skopje, North Macedonia",
  "Sofia, Bulgaria",
  "South Tarawa, Kiribati",
  "Sri Jayawardenepura Kotte, Sri Lanka",
  "St. Louis, United States",
  "Stanley, Falkland Islands",
  "Stockholm, Sweden",
  "Sucre, Bolivia",
  "Surabaya, Indonesia",
  "Surat, India",
  "Suva, Fiji",
  "Sydney, Australia",
  "Tabriz, Iran",
  "Taichung, Taiwan",
  "Tainan, Taiwan",
  "Taipei, Taiwan",
  "Tallinn, Estonia",
  "Tampa, United States",
  "Tashkent, Uzbekistan",
  "Tbilisi, Georgia",
  "Tegucigalpa, Honduras",
  "Tehran, Iran",
  "Tel Aviv, Israel",
  "Thimphu, Bhutan",
  "Tianjin, China",
  "Tijuana, Mexico",
  "Tirana, Albania",
  "Tokyo, Japan",
  "Toronto, Canada",
  "Torshavn, Faroe Islands",
  "Tripoli, Libya",
  "Tunis, Tunisia",
  "Ulaanbaatar, Mongolia",
  "Vaduz, Liechtenstein",
  "Valletta, Malta",
  "Vancouver, Canada",
  "Victoria, Seychelles",
  "Vienna, Austria",
  "Vientiane, Laos",
  "Vilnius, Lithuania",
  "Warsaw, Poland",
  "Washington, D.C., United States",
  "Wellington, New Zealand",
  "Windhoek, Namibia",
  "Yamoussoukro, Ivory Coast",
  "Yaounde, Cameroon",
  "Yerevan, Armenia",
  "Zagreb, Croatia",
  "Zurich, Switzerland",
];
